---
title: "Extended data Figure 7"
site: workflowr::wflow_site
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
      code_folding: hide
chunk_output_type: console
---


```{r packages}
library(tidyverse)
library(magrittr)
library(stringr)
library(devtools)
library(here)
load_all(here("code", "rlucas"))
data(prediction_lucas, package="rlucas")
data(metadata, package="rlucas")
```

```{r protein_scatter, fig.height=4, fig.width=15,dev=c("png", "pdf")}
meta <- left_join(preds, meta, by="id")
proteins <- meta %>% filter(assigned_group == 2) %>%
    select(score.seq, IL6,  CEA, CRP, YKL40) %>%
    pivot_longer(-score.seq,  names_to="Protein")
rhos <- proteins %>% group_by(Protein) %>%
    summarize(corr = round(cor(score.seq, value,
                               use="complete.obs",
                               method="spearman"), 2)) %>%
    mutate(label = sprintf("\"Spearman's\" ~ rho == %0.2f", corr))


base_size <- 20
mytheme <- theme_bw(base_size=base_size)  +
    theme(panel.background=element_rect(fill="white",
                                        color="white"),
          panel.grid=element_blank(),
          rect=element_blank(),
          axis.line.y=element_blank(),
          axis.line.x.bottom=element_line(color="black"),
    strip.placement="outside")

ggprotein <- ggplot(proteins, aes(value, score.seq)) + geom_point(size=1) +
    scale_x_continuous(trans='log10') +
    facet_grid(.~Protein, scales="free_x", space="fixed", switch="x") +
    xlab("") + ylab(expression("DELFI score")) +
    ylim(c(0, 1)) +
    geom_segment( x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size=1.5) +
    geom_text(data=rhos, aes(label=label), size = 4.5, color="red",
              x=Inf, y=Inf, hjust=1.0, vjust=1.2, parse=TRUE) +
    mytheme
ggprotein
```
