---
title: "Distribution of DELFI scores by T stage and N stage"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r packages}
library(SummarizedExperiment)
library(tidyverse)
library(magrittr)
library(stringr)
library(survival)
library(survminer)
library(ggplot2)
library(readxl)
library(here)
library(devtools)
load_all(here("code", "rlucas"))
data(prediction_lucas, package="rlucas")
data(metadata, package="rlucas")
```

## Figure 4c (Kaplan-Meier curves)

```{r survdata}
data(se, package="rlucas")
path <- system.file("extdata", package="rlucas")
surv_samples <- read_excel(file.path(path, "survival_analysis_samples.xlsx"), sheet=1,
                           skip=1) %>%
    select(pgdx_id)
coldat <- colData(se) %>%
    as_tibble()
dat <- coldat %>%
    filter(pgdx_id %in% surv_samples$pgdx_id) %>%
    mutate(delfi.full=ifelse(score_full_lasso2 > 0.5, 1, 0),
           delfi.seq=ifelse(score_seq > 0.5, 1, 0)) %>%
    mutate(is_deceased=ifelse(survival=="Deceased", 1, 0))
stopifnot(all(dat$assigned_group==3))
stopifnot(all(dat$histology%in%c("SCLC", "Adenocarcinoma", "Squamous")))
```


```{r survcurve_seq, fig.width=10, fig.height=6,dev=c("png", "pdf")}
dat$survival <- with(dat, Surv(days_alive, is_deceased))
fit <- survfit(survival ~ delfi.seq, data = dat)
fig <- ggsurvplot(fit, data = dat,
           surv.median.line = "hv", ## Add medians survival
           ## Add p-value and tervals
           pval = FALSE,
           conf.int = FALSE,
           ## Add risk table
           risk.table = FALSE,
           tables.height = 0.2,
           tables.theme = theme_cleantable(),
           axes.offset=FALSE,
           ## Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
           ## or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
           ##palette = c("#E7B800", "#2E9FDF"),
           legend=c(0.75, 0.8),
           legend.title="", 
           palette=c("blue", "red"),
           legend.labs=c("DELFI < 0.5", "DELFI > 0.5"),
           ##legend.labs=labels,
           ggtheme = theme_classic(base_size=20) # Change ggplot2 theme
           ) +
    ylab("Cancer-specific survival\n") +
    xlab("Days")
medians <- surv_median(fit)$median
breaks <- sort(c(seq(0, 3000, by=1000), medians)) 
breaks <- breaks[ breaks != 1000 ]
fig$plot <- fig$plot  +
    scale_x_continuous(breaks=breaks, expand=expansion(mult=c(0, 0.01)))
X2 <- survdiff(Surv(days_alive, is_deceased) ~ delfi.seq, data=dat)$chisq
p <- round(1-pchisq(X2, df=1), 4)
if(p < 0.001){
    plabel <- "P < 0.001"
} else {
    plabel <- paste0("P = ", round(p, 3))
}
fig$plot <- fig$plot + annotate("text", x=2000, y=0.3, label=plabel,
                                size=5)
print(fig$plot)
```



