---
title: "Relative coverage plot and ROC"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
editor_options:
  chunk_output_type: console
---


```{r caching, echo=FALSE}
knitr::opts_chunk$set(autodep = TRUE, echo=FALSE)
```


```{r load_data, echo=FALSE, include=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(pROC)
library(purrr)
library(here)
```


```{r panel_c}
roc <- pROC::roc
df <- read.table(here("data", "ascl1_rel_cov_10v10.txt"),
                 header = TRUE, stringsAsFactors = FALSE, sep = "\t") %>%
    as_tibble() %>%
    mutate(analysis="No baseline cancer")
```


```{r column1}
df2 <- read.table(here("data", "all_sclc_vs_all_healthy_tfbs_coverage.txt"),
                  header = TRUE, stringsAsFactors = FALSE, sep = "\t") %>%
    as_tibble() %>%
    mutate(analysis="Other") 
colors <- setNames(c("gray", "slateblue", "gray"), unique(df2$grp))
panel_c <- df %>%
    ggplot(aes(x = pos, y = rel_cov,
               color = grp,
               group = id)) +
    theme_classic(base_size=20) +
    geom_line() +
    geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
    ylim(c(0.5, 1)) +
    ylab("Relative coverage") +
    xlab("Position relative to TFBS (bp)") +
    scale_color_manual(values = colors) +
    scale_x_continuous(expand=expansion(add=0, mult=c(0, 0.05)),
                       breaks=seq(-3000, 3000, 1000)) +
    theme(legend.title = element_blank(),
          legend.position = c(0.7, 0.2))
##panel_d <- df2 %>%
##    ggplot(aes(x = pos,
##               y = rel_cov,
##               color = grp,
##               group = id)) +
##    geom_line() +        
##    theme_classic(base_size=20) +
##    geom_line(data=filter(df2, grp=="SCLC"),
##              color="slateblue") +    
##    geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
##    ylim(c(0.5, 1)) +
##    ylab("Relative coverage") +
##    xlab("Position relative to TFBS (bp)") +
##    scale_color_manual(values = colors) +
##    scale_x_continuous(expand=expansion(add=0, mult=c(0, 0.05)),
##                       breaks=seq(-3000, 3000, 1000)) +
##    theme(legend.title = element_blank(),
##          legend.position = c(0.7, 0.2))
```

```{r roc_analysis}
# Computing a relative coverage metric for each sample for the ROC curve
df <- df2
ids <- unique(df$id)
ctl_pos <- c(-3000:-2500, 2500:3000)
dip_pos <- -100:100
summary.df <- data.frame(id = character(0),
                         grp = character(0),
                         rel_cov = character(0))
for (i in 1:length(ids)) {
    z <- subset(df, id == ids[i])
    rel_cov <- ( sum(z$cov[z$pos %in% dip_pos]) / length(dip_pos) ) /
        ( sum(z$cov[z$pos %in% ctl_pos]) / length(ctl_pos) )
    tmp.summary.df <- data.frame(id = ids[i],
                                 grp = unique(df$grp[df$id == ids[i]]),
                                 rel_cov = rel_cov)
    summary.df <- rbind(summary.df, tmp.summary.df)
}
# Creating the ROC curve
roc.res <- pROC::roc(summary.df$grp, summary.df$rel_cov, ci = TRUE)

dat <- tibble(sens=roc.res$sensitivities,
              spec=roc.res$specificities) %>%
    arrange(sens)
ci_roc <- roc.res$ci
roc_label <- paste0("AUC: ", round(roc.res$auc[[1]], 2),
                    " (",
                    round(ci_roc[[1]], 2),
                    "-",
                    round(ci_roc[[2]], 2),
                    ")")
panel_d <- dat %>%
    ggplot(aes(spec, sens)) + 
    geom_vline(xintercept=0.80,
               color="gray80", size=0.5, linetype="dashed") +
    geom_line(size=1.1) +
    scale_x_reverse(expand=c(0, 0.01),
                    breaks=c(0, 0.25, 0.5, 0.80, 1),
                    labels=as.character(
                        c("0", ".25", ".50", ".80", "1.0"))) +
    scale_y_continuous(expand=c(0, 0.01),
                       breaks=c(0, 0.25, 0.5, 0.75, 1),
                       labels=as.character(
                           c("0", ".25", ".50", ".75", "1.0"))) +
    theme_classic(base_size=20) +
    theme(panel.grid=element_blank(),
          legend.position=c(0.6, 0.2),
          aspect.ratio=0.8,
          legend.text.align=1,
          legend.title=element_text(size=16)) +
    xlab("Specificity") + ylab("Sensitivity") +
    annotate("text", x=0.3, y=0.3, label=roc_label,
             size=5)
```


```{r panel_e}
df <- read.table(here("data", "tfbs_coverage.txt"),
                 header = TRUE, stringsAsFactors = FALSE)

# Computing relative coverage
ids <- unique(df$id)
df$rel_cov <- NA
for (i in 1:length(ids)) {
  id.hits <- which(df$id == ids[i])
  df$rel_cov[id.hits] <- df$cov[id.hits] / max(df$cov[id.hits])
}

# Plotting relative coverage for all samples separately
df$grp <- factor(df$grp, levels = c("Other", "SCLC"))
id_ord <- c(unique(subset(df, grp == "Other")$id), unique(subset(df, grp == "SCLC")$id))
df$id <- factor(df$id, levels = id_ord)

# Plotting the non-SCLC group as the median and the 0.05 and 0.95 quantiles
q.df <- df %>%
          filter(grp != "SCLC") %>%
          group_by(pos) %>%
          summarise(q5 = quantile(rel_cov, 0.05),
                    m = median(rel_cov),
                    q95 = quantile(rel_cov, 0.95)) %>%
          as.data.frame

sclc.df <- subset(df, grp == "SCLC")

# Adding the median of the 'Other' group to sclc.df
median.df <- data.frame(id = "Other_median",
                        grp = "Other",
                        pos = q.df$pos,
                        cov = NA,
                        rel_cov = q.df$m)
sclc.df <- rbind(median.df, sclc.df)
sclc.df$grp <- factor(sclc.df$grp, levels = c("SCLC", "Other"))

# Plotting the relative coverage at the TFBS
panel_e <- ggplot(sclc.df, aes(x = pos, y = rel_cov, color = grp, group = id)) +
    geom_ribbon(data = q.df, aes(x = pos, ymin = q5, ymax = q95),
                inherit.aes = FALSE, alpha = 0.5, color = NA, fill = "grey50") +
    geom_line(aes(color = grp), alpha = 0.8) +
    ##cowplot::theme_cowplot() +
    theme_classic(base_size=20) +
    scale_color_manual(values = colors) +
    scale_x_continuous(expand=expansion(add=0, mult=c(0, 0.05)),
                       breaks=seq(-3000, 3000, 1000)) +        
    geom_vline(xintercept = 0, linetype = "dashed", color = "grey") +
    ylim(c(0.5, 1)) +
    ylab("Relative coverage") +
    xlab("Position relative to TFBS (bp)") +
    scale_color_manual(values = c(Other = "black", SCLC = "slateblue")) +
    theme(legend.title = element_blank(),
          legend.position = c(0.7, 0.2))
```


```{r panel_f}
# Computing a relative coverage metric for each sample for the ROC curve
ctl_pos <- c(-3000:-2500, 2500:3000)
dip_pos <- -100:100
summary.df <- data.frame(id = character(0),
                         grp = character(0),
                         rel_cov = character(0))
for (i in 1:length(ids)) {
  z <- subset(df, id == ids[i])
  rel_cov <- ( sum(z$cov[z$pos %in% dip_pos]) / length(dip_pos) ) / ( sum(z$cov[z$pos %in% ctl_pos]) / length(ctl_pos) )
  tmp.summary.df <- data.frame(id = ids[i],
                               grp = unique(df$grp[df$id == ids[i]]),
                               rel_cov = rel_cov)
  summary.df <- rbind(summary.df, tmp.summary.df)
}
# Creating the ROC curve
roc.res <- pROC::roc(summary.df$grp, summary.df$rel_cov, ci = TRUE)

dat <- tibble(sens=roc.res$sensitivities,
              spec=roc.res$specificities) %>%
    arrange(sens)
ci_roc <- roc.res$ci
roc_label <- paste0("AUC: ", round(roc.res$auc[[1]], 2),
                    " (",
                    round(ci_roc[[1]], 2),
                    "-",
                    round(ci_roc[[2]], 2),
                    ")")
panel_f <- dat %>%
    ggplot(aes(spec, sens)) + 
    geom_vline(xintercept=0.80,
               color="gray80", size=0.5, linetype="dashed") +
    geom_line(size=1.1) +
    scale_x_reverse(expand=c(0, 0.01),
                    breaks=c(0, 0.25, 0.5, 0.80, 1),
                    labels=as.character(
                        c("0", ".25", ".50", ".80", "1.0"))) +
    scale_y_continuous(expand=c(0, 0.01),
                       breaks=c(0, 0.25, 0.5, 0.75, 1),
                       labels=as.character(
                           c("0", ".25", ".50", ".75", "1.0"))) +
    theme_classic(base_size=20) +
    theme(panel.grid=element_blank(),
          legend.position=c(0.6, 0.2),
          aspect.ratio=0.8,
          legend.text.align=1,
          legend.title=element_text(size=16)) +
    xlab("Specificity") + ylab("Sensitivity") +
    annotate("text", x=0.3, y=0.3, label=roc_label,
             size=5)
```


```{r daniel_composite, fig.height = 7, fig.width = 15, dev = c("png", "pdf")}
cowplot::plot_grid(panel_c, panel_d,
                   panel_e, panel_f,
                   ncol = 2, rel_widths = c(0.6, 0.4, 0.6, 0.4))
```



