---
title: "SessionInfo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
#2
library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(data.table)
library(cowplot)
library(devtools)
library(here)
library(tidyverse)
library(openxlsx)
library(devtools)
library(ComplexHeatmap)
library(circlize)
library(data.table)
library(here)
library(tidyverse)
library(data.table)
library(grid)
library(gridExtra)
library(here)
library(tidyverse)
library(caret)
library(recipes)
library(pROC)
library(devtools)
library(reshape2)
library(plyr)
library(gridExtra)
library(grid)
library(here)

#3
library(SummarizedExperiment)
library(devtools)
library(magrittr)
library(stringr)
library(tidyverse)
library(grid)
library(lemon)
library(gridExtra)
library(cowplot)
library(data.table)
library(pROC)
library(RColorBrewer)
library(here)


#4
library(readxl)
library(ggplot2)
library(here)
library(SummarizedExperiment)
library(tidyverse)
library(magrittr)
library(stringr)
library(survival)
library(survminer)
library(ggplot2)
library(readxl)
library(here)
library(devtools)

#5
library(ggplot2)
library(here)
library(ggplot2)
library(pheatmap)
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(pROC)
library(purrr)
library(here)

#6
library(RColorBrewer)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(readxl)
library(magrittr)
library(grid)
library(gridExtra)
library(here)
library(hrbrthemes)
library(viridis)
library(kableExtra)
library(jcolors)
library(ggplot2)
library(magrittr)
library(tidyverse)
library(fs)
library(grid)
library(mvtnorm)
library(readxl)
library(kableExtra)
library(here)

#extended 2
library(tidyverse)
library(ggplot2)
library(SummarizedExperiment)
library(paletteer)
library(ggsci)
library(here)
library(devtools)
library(RColorBrewer)
library(SummarizedExperiment)
library(magrittr)
library(tidyverse)
library(ggplot2)
library(here)

#extended 3
library(tidyverse)
library(caret)
library(recipes)
library(pROC)
library(devtools)
library(glmnet)
library(reshape2)
library(here)

#extended 4
library(tidyverse)
library(magrittr)
library(stringr)
library(gridExtra)
library(broom)
library(SummarizedExperiment)
library(devtools)
library(here)

#extended 5
library(tidyverse)
library(magrittr)
library(stringr)
library(devtools)
library(here)

#extended 6
library(pROC)
library(readxl)
library(here)
library(readxl)
library(tidyverse)
library(caret)
library(pROC)
library(precrec)
library(here)
library(RColorBrewer)
library(SummarizedExperiment)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(magrittr)
library(here)
library(devtools)


#extended 7
library(devtools)
library(data.table)
library(caret)
library(recipes)
library(magrittr)
library(tidyr)
library(purrr)
library(cowplot)
library(devtools)
library(here)

#extended 8
library(tidyverse)
library(magrittr)
library(lemon)
library(broom)
library(stringr)
library(SummarizedExperiment)
library(devtools)
library(here)

#extended 9
library(SummarizedExperiment)
library(devtools)
library(magrittr)
library(stringr)
library(tidyverse)
library(grid)
library(lemon)
library(gridExtra)
library(cowplot)
library(data.table)
library(pROC)
library(RColorBrewer)
library(here)

#extended 10
library(here)
library(ggplot2)
library(dplyr)
library(ggplot2)
library(pROC)
library(here)
library(dplyr)
library(ggplot2)
library(pROC)
library(here)

#extended 11
library(SummarizedExperiment)
library(tidyverse)
library(magrittr)
library(stringr)
library(survival)
library(survminer)
library(ggplot2)
library(readxl)
library(tidyr)
library(broom)
library(gridExtra)
library(kableExtra)
library(tidyr)
library(devtools)
library(here)

#extended 12
library(SummarizedExperiment)
library(tidyverse)
library(magrittr)
library(stringr)
library(survival)
library(survminer)
library(ggplot2)
library(readxl)
library(tidyr)
library(broom)
library(gridExtra)
library(kableExtra)
library(tidyr)
library(devtools)
library(here)

#models
library(tidyverse)
library(caret)
library(recipes)
library(pROC)
library(devtools)
library(here)
library(tidyverse)
library(caret)
library(recipes)
library(pROC)
library(devtools)
library(openxlsx)
library(precrec)
library(tidyverse)
library(caret)
library(pROC)
library(readxl)
library(DT)
library(recipes)
library(devtools)
library(data.table)
library(here)
library(devtools)
library(here)
library(tidyverse)
library(caret)

#Delfi Pipeline
suppressMessages(library(GenomicAlignments))
suppressMessages(library(GenomicRanges))
suppressMessages(library(Rsamtools))
suppressMessages(library(devtools))
suppressMessages(library(Biostrings))
suppressMessages(library(data.table))
suppressMessages(library(getopt))
suppressMessages(library(devtools))
library(PlasmaTools.lucas)
library(PlasmaToolsHiseq.hg19)



```

```{r info}
sessionInfo()
```

